name: Instagram Sync

on:
  schedule:
    - cron: '0 2 * * *'   # 02:00 UTC = 03:00 Paris
  workflow_dispatch:

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'
        cache: 'npm'

    - name: Install dependencies
      run: npm ci

    - name: Run Instagram sync
      env:
        AIRTABLE_API_KEY: ${{ secrets.AIRTABLE_API_KEY }}
        AIRTABLE_BASE_ID:  ${{ secrets.AIRTABLE_BASE_ID }}
      run: node scrap-instagram-simple.js